# Generated by Django 4.2 on 2025-10-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APILaboratoristas', '0001_initial'),
        ('APIPaciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('hdl', models.CharField(max_length=255)),
                ('ldl', models.CharField(max_length=255)),
                ('trigliceridos', models.CharField(max_length=255)),
                ('cod_ingreso', models.ForeignKey(db_column='cod_ingreso', on_delete=django.db.models.deletion.CASCADE, to='APIPaciente.pacientes')),
                ('cod_laboratorista', models.ForeignKey(db_column='cod_laboratorista', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APILaboratoristas.laboratoristas')),
            ],
            options={
                'db_table': 'Resultados',
            },
        ),
    ]
