# Generated by Django 4.2 on 2025-10-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratoristas',
            fields=[
                ('cod_laboratorista', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('profesion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Laboratoristas',
            },
        ),
    ]
